### ISSUE TITLE
Game Loop Mechanic

### ISSUE THREAD

**Issue by Docter60** [flaccorice27/Game-V2#2]

**Comment by flaccorice27** [comment]
http://zetcode.com/gfx/java2d/

https://docs.oracle.com/javase/tutorial/uiswing/misc/timer.html

Some stuff to look at for this. If we can't figure this out, we could consider switching to something other than Java, but I'd like to figure this out in Java as it would be an accomplishment

**Comment by Docter60** [comment]
JavaFX may be worth looking into.  We may have a better time using JavaFX but I certainly would have to learn the structure. [This](https://gamedevelopment.tutsplus.com/tutorials/introduction-to-javafx-for-game-development--cms-23835) looks like a good place to start if we want to do this.

**Comment by flaccorice27** [comment]
Closing as issue is reopened in proper milestone
